### ISSUE TITLE
Tablas/datos

### ISSUE THREAD

**Issue by jbkunst** [visualizacionuc/introduccion-datos#1]
Don @palamago,

¿En sus clases, hasta ahora, ha existido un data set o tabla que haya sido de interés para los alumnos? Esto con el fin de hacer ejemplos con datos que ya conozcan y no hacer una introducción a los mismos :sweat_smile: .

**Comment by palamago** [comment]
Usé uno muy pequeño sobre el top 5 de películas ganadores del Óscar, nada serio. 😄
